apiVersion: v2
name: uidam-web-admin-portal
description: UIDAM Web Admin Portal - React-based administration interface
type: application
version: 0.0.1
appVersion: "1.0.0"
keywords:
  - uidam
  - portal
  - admin
  - react
  - web
maintainers:
  - name: HARMAN Auto Team
