apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uidam-authorization-server.fullname" . }}
  labels: {{- include "uidam-authorization-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "uidam-authorization-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-addr: "{{ .Values.vault.url }}"
        vault.security.banzaicloud.io/vault-role: "{{ include "uidam-authorization-server.fullname" . }}-role"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config-tenants: {{ include (print $.Template.BasePath "/configmap-tenants-config.yaml") . | sha256sum }}
        checksum/config-default: {{ include (print $.Template.BasePath "/configmap-default-configurations.yaml") . | sha256sum }}
      labels: {{- include "uidam-authorization-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "uidam-authorization-server.fullname" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "{{ .Values.metrics.basePath }}/health/liveness"
            port: {{ .Values.metrics.prometheus.agent.port }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
        readinessProbe:
          httpGet:
            path: "{{ .Values.metrics.basePath }}/health/readiness"
            port: {{ .Values.metrics.prometheus.agent.port }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
        envFrom:
        - configMapRef:
            name: {{ include "uidam-authorization-server.fullname" . }}
        {{- range $tenantKey, $tenantConfig := .Values.multiTenant.tenants }}
        {{- if ne $tenantKey "default" }}
        {{- if or (contains $tenantKey $.Values.multiTenant.tenantIds) (eq $tenantKey $.Values.multiTenant.defaultTenant) }}
        - configMapRef:
            name: {{ include "uidam-authorization-server.fullname" $ }}-tenant-{{ $tenantKey }}
        {{- end }}
        {{- end }}
        {{- end }}
        - configMapRef:
            name: {{ include "uidam-authorization-server.fullname" . }}-tenant-default
        volumeMounts:
          - name: uidam-jks
            mountPath: /etc/uidam/keystore
          - mountPath: /tmp/uidamCustomUI
            subPath: igniteShared/uidamCustomUI/
            name: uidam-shared-storage
          - name: app-keys
            mountPath: /etc/uidam/cert
        resources: {{- toYaml .Values.resources | nindent 10 }}         
      initContainers:
        - name: postgresql-initializer
          image: "{{ .Values.postgres.initializer.image.repository }}:{{ .Values.postgres.initializer.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.initializer.image.pullPolicy }}
          env:
            - name: LOGLEVEL
              value: DEBUG
            - name: POSTGRESQL_CONFIG_FILE
              value: /data/uidam-authorization-server-postgres-config.yml
            - name: POSTGRESQL_HOST
              value: "{{ .Values.postgres.host }}"
            - name: POSTGRESQL_PORT
              value: "{{ .Values.postgres.port }}"
            - name: POSTGRESQL_USERNAME
              value: vault:{{ .Values.vault.secretsEnginePath }}/data/{{ include "uidam-authorization-server.fullname" . }}#username
            - name: POSTGRESQL_PASSWORD
              value: vault:{{ .Values.vault.secretsEnginePath }}/data/{{ include "uidam-authorization-server.fullname" . }}#password
          volumeMounts:
            - mountPath: /data
              name: uidam-authorization-server-postgresql-config
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: uidam-authorization-server-postgresql-config
          configMap:
            name: uidam-authorization-server-postgresql-config
        - name: uidam-jks
          configMap:
            name: {{ include "uidam-authorization-server.fullname" . }}-jks
        - name: uidam-shared-storage
          persistentVolumeClaim:
            claimName: {{ .Values.sharedStoragePvcName }}
        - name: app-keys
          configMap:
            name: {{ include "uidam-authorization-server.fullname" . }}-app
          
