apiVersion: v1
kind: PersistentVolume
metadata:
  name: "aws-efs-uidam-shared-storage"
  labels:
    {{- include "uidam-authorization-server.labels" . | nindent 4 }}
    usage: shared
spec:
  capacity:
    storage: "1Gi"
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "{{ .Values.nfsServerUrl }}"
    path: /