apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uidam-user-management.fullname" . }}
  labels: {{- include "uidam-user-management.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "uidam-user-management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        vault.security.banzaicloud.io/vault-skip-verify: "true"
        vault.security.banzaicloud.io/vault-addr: "{{ .Values.vault.url }}"
        vault.security.banzaicloud.io/vault-role: "{{ include "uidam-user-management.fullname" . }}-role"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config-tenants: {{ include (print $.Template.BasePath "/configmap-tenants-config.yaml") . | sha256sum }}
        checksum/config-default: {{ include (print $.Template.BasePath "/configmap-default-configurations.yaml") . | sha256sum }}
      labels: {{- include "uidam-user-management.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "uidam-user-management.fullname" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext: {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.path }}
            port: {{ .Values.probes.liveness.port }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.path }}
            port: {{ .Values.probes.readiness.port }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
        envFrom:
        - configMapRef:
            name: {{ include "uidam-user-management.fullname" . }}
        {{- range $tenantKey, $tenantConfig := .Values.multiTenant.tenants }}
        {{- if ne $tenantKey "default" }}
        {{- if or (contains $tenantKey $.Values.multiTenant.tenantIds) (eq $tenantKey $.Values.multiTenant.defaultTenant) }}
        - configMapRef:
            name: {{ include "uidam-user-management.fullname" $ }}-tenant-{{ $tenantKey }}
        {{- end }}
        {{- end }}
        {{- end }}
        - configMapRef:
            name: {{ include "uidam-user-management.fullname" . }}-tenant-default
        resources: {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /notification
          name: {{ .Values.notification.config.configName }}
      initContainers:
        - name: postgresql-initializer
          image: "{{ .Values.postgres.initializer.image.repository }}:{{ .Values.postgres.initializer.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.initializer.image.pullPolicy }}
          env:
            - name: LOGLEVEL
              value: DEBUG
            - name: POSTGRESQL_CONFIG_FILE
              value: /data/uidam-user-management-postgres-config.yml
            - name: POSTGRESQL_HOST
              value: "{{ .Values.postgres.host }}"
            - name: POSTGRESQL_PORT
              value: "{{ .Values.postgres.port }}"
            - name: POSTGRESQL_USERNAME
              value: vault:{{ .Values.vault.secretsEnginePath }}/data/{{ include "uidam-user-management.fullname" . }}#username
            - name: POSTGRESQL_PASSWORD
              value: vault:{{ .Values.vault.secretsEnginePath }}/data/{{ include "uidam-user-management.fullname" . }}#password
          volumeMounts:
            - mountPath: /data
              name: uidam-user-management-postgresql-config
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: uidam-user-management-postgresql-config
          configMap:
            name: uidam-user-management-postgresql-config
        - name: {{ .Values.notification.config.configName }}
          configMap:
            name: {{ .Values.notification.config.configName }}
            optional: true