apiVersion: vault.harman.com/v1alpha1
kind: VaultPolicy
metadata:
  name: {{ include "uidam-user-management.fullname" . }}
  labels: {{- include "uidam-user-management.labels" . | nindent 4 }}
spec:
  policyDocument: |
    path "{{ .Values.vault.secretsEnginePath }}/data/uidam-user-management" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }
    path "database/creds/{{ .Values.vault_init.vault_secret_folder }}-postgres-role" {
      capabilities = ["read", "list"]
    }
