apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uidam-web-admin-portal.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "uidam-web-admin-portal.labels" . | nindent 4 }}
  annotations:
    vault.security.banzaicloud.io/mutate-configmap: "true"
data:
  REACT_APP_OAUTH_CLIENT_SECRET: "vault:{{ .Values.vault.secretsEnginePath }}/data/{{ .Values.vault_init.vault_secret_folder }}#clientSecret"
